#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

rm -rf $1/app/BackupAndRestore
rm -rf $1/app/BTtestmode
rm -rf $1/app/Calculator2
rm -rf $1/app/ChildrenSpace
rm -rf $1/app/EmailPartnerProvider
rm -rf $1/app/FindMyPhoneClient
rm -rf $1/app/GameSpace
rm -rf $1/app/Ocrscanner
rm -rf $1/app/Oshare
rm -rf $1/app/ModemTestMode
rm -rf $1/app/NewSoundRecorder
rm -rf $1/app/talkback
rm -rf $1/app/FM2
rm -rf $1/app/Maps
rm -rf $1/app/Keep
rm -rf $1/app/Gmail2
rm -rf $1/app/GoogleTTS
rm -rf $1/app/NewSoundRecorder
rm -rf $1/app/OppoCamera
rm -rf $1/app/OppoCompass2
rm -rf $1/app/OppoDCS
rm -rf $1/app/Youtube
rm -rf $1/app/SecurePay
rm -rf $1/app/SecureElement
rm -rf $1/app/SafeCenter
rm -rf $1/priv-app/Blacklist
rm -rf $1/priv-app/BlacklistApp
rm -rf $1/priv-app/TestApp5G
rm -rf $1/priv-app/com.facebook.system
rm -rf $1/priv-app/SmartDrive
rm -rf $1/priv-app/OppoMusic
rm -rf $1/priv-app/OppoBootReg
rm -rf $1/priv-app/OppoGallery2
rm -rf $1/priv-app/VideoGallery
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/VideoGallery
rm -rf $1/reserve
rm -rf $1/app/com.amazon.appmanager
rm -rf $1/app/com.facebook.appmanager
rm -rf $1/app/KeKeMarket
rm -rf $1/app/KeKePay
rm -rf $1/app/KeKeUserCenter
rm -rf $1/app/NXPNfcNci
rm -rf $1/app/OcrScanner
rm -rf $1/app/OcrService
rm -rf $1/app/AssistantScreen
rm -rf $1/app/AutoRegistration
rm -rf $1/app/AvastOfferWall
rm -rf $1/app/ChildrenSpace
rm -rf $1/app/colorservice
rm -rf $1/app/datastatusnotification
rm -rf $1/app/Gamecenter
rm -rf $1/app/uimremoteclient
rm -rf $1/app/uimremoteserver
rm -rf $1/app/uceShimService
rm -rf $1/app/ModemTestMode
rm -rf $1/app/HealthCheck
rm -rf $1/app/FidoCryptoService
rm -rf $1/app/Shelper
rm -rf $1/app/SoterService
rm -rf $1/app/Keep
rm -rf $1/app/RomUpdate
rm -rf $1/app/OppoLogKit
rm -rf $1/app/OShare
rm -rf $1/app/OppoDCS
rm -rf $1/app/OVoiceManagerService
rm -rf $1/app/OppoChromeCustomizations
rm -rf $1/app/OppoOperationManualExp
rm -rf $1/app/OppoCompass2
rm -rf $1/app/OppoDropboxChmodService
rm -rf $1/app/OppoPartnerBookmarksProvider
rm -rf $1/app/OppoPhoneActivationExp
rm -rf $1/app/OppoQualityProtect
rm -rf $1/app/OppoSmallWeatherWidget
rm -rf $1/app/OppoTranslationService
rm -rf $1/app/OppoWeather2
rm -rf $1/app/OppoWeatherService
rm -rf $1/app/OppoWifiSniffer
rm -rf $1/app/PhoneManager
rm -rf $1/app/RealmeWidevineService
rm -rf $1/app/SafeCenter
rm -rf $1/app/SafeSdkProxy
rm -rf $1/app/SecurePay
rm -rf $1/app/com.facebook.appmanager
rm -rf $1/app/talkback
rm -rf $1/app/KeKePay
rm -rf $1/app/KeKeUserCenter
rm -rf $1/app/KeKeMarket
rm -rf $1/app/OTA
rm -rf $1/app/OTAUI
rm -rf $1/priv-app/GlobalSearch
rm -rf $1/priv-app/LogTool
rm -rf $1/priv-app/NumberRecognition
rm -rf $1/priv-app/SmartDrive
rm -rf $1/priv-app/Omacp
rm -rf $1/priv-app/SoftsimRedteaRoaming
rm -rf $1/priv-app/SoftsimRedteaRoamingDeamon
rm -rf $1/priv-app/com.LogiaGroup.LogiaDeck
rm -rf $1/priv-app/com.app.m1remit
rm -rf $1/priv-app/com.facebook.services
rm -rf $1/priv-app/com.facebook.system
rm -rf $1/priv-app/com.korvac.liquid
rm -rf $1/priv-app/com.m1.mym1
rm -rf $1/priv-app/com.singtel.mysingtel
rm -rf $1/priv-app/deezer.android.app
rm -rf $1/priv-app/sg.gov.mnd.OneService"
